views/apply-pg.php
views/apply-ug.php

Fixes https://github.com/unikent/programmes-plant/issues/815
(for PG only)
mode of study in programmes plant sometimes conflicts with mode of study in SITS
e.g. http://www.kent.ac.uk/courses/postgraduate/apply-online/214 (PP - FT only, SITS - FT and PT)
This refactor only displays the mode of study option on interim apply page if PP == SITS delivery

refactor pg apply

---

views/pg_tabs/structure.php
views/ug_tabs/structure.php

See line 97 - end section outside if statement or page breaks for module session = none
Other changes are just whitespace

end section tag correctly

---

views/pg_tabs/structure.php

don't output heading if no content

---

views/pg_course_page.php
views/pg_tabs/structure.php

Show taught postgraduate structure tab always

---

views/pg_tabs/careers.php

fixes FP#638743. pull in after @aw285-unikent's go-ahead.

make careers header consistent

---

views/apply-pg.php
views/apply-ug.php
views/pg_course_page.php
views/pg_tabs/apply.php
views/ug_course_page.php

add admin school to ga events

---

views/layout.php

Another meta needing removed

---

views/pg_search.php
views/ug_search.php

addresses https://github.com/unikent/of-course/issues/708

Sort subject categories before displaying

---

views/pg_course_page.php
views/ug_course_page.php

Remove oversees part-time fees

---

public/css/courses.css
public/css/courses.less

Add styles for student blog link

---

main/main.php

Allow reuse in other methods.
Addresses FP#682837

Refactor location and awards

---

main/main.php

Call locations_str properly

---

views/ug_search.php

Remove remarketing tag

---

app/controllers/CoursesController.php
app/views/pg_course_page.php
app/views/ug_course_page.php

Add ability to disable apply links per year

---

app/views/apply-pg.php

Detect when a delivery can not be uniquely identify by the filters available & show full listing instead.

Add edge case exception for apply page

---

app/views/pg_tabs/enquiries.php

Remove graduate school

---

app/views/ug_course_page.php
app/views/ug_tabs/enquiries.php

see: https://trello.com/c/Ag8R6xjV/263-ensure-kis-widget-complies-with-hesa-display-guidelines

show KIS widget on course landing

---

app/views/ug_course_page.php

see: https://trello.com/c/4BrZxCoV/303-stop-kis-widget-outputting-on-suspended-programmes

dont show KIS widget for suspended programmes

---

app/views/pg_course_page.php
app/views/ug_course_page.php

see: https://github.com/unikent/programmes-plant/pull/881

change fees output to use new format

---

app/lib/utils.php
app/views/modules/index.php
app/views/modules/module.php
public/css/module-catalogue.css
public/css/module-catalogue.less

Requires https://github.com/unikent/pantheon/pull/1438 (update central copy of QS to latest version)

Setup quickspot search on module pages.

---

app/controllers/ModulesController.php
app/lib/utils.php
app/routes.php
app/views/modules/disclaimer.php
app/views/modules/index.php
app/views/modules/module.php
public/css/module-catalogue.css
public/css/module-catalogue.less

See: https://trello.com/c/jcp6TUSn/30-disclaimer-page and https://trello.com/c/7LPJCH8E/31-don-t-output-tab-if-no-content

add disclaimer copy & omit empty tabs

---

app/views/ug_search.php

should probably not hard code this

Change year

---

app/views/ug_search.php

https://trello.com/c/Ka6iiN8L/533-change-dropdown-on-course-search-so-foundation-year-displays-all-foundation-and-ifp-programmes

Course options - IFP/Foundation

---

app/controllers/CoursesController.php
app/lib/utils.php
app/views/pg_search.php

Fix study abroad pages

---

app/controllers/CoursesController.php
app/views/apply-pg.php
app/views/apply-ug.php

Angela would like this to go live on 31st May. This branch was tested on www-test

Feature/aways show apply interim page [Roll live on Tuesday 31st May]

---

app/views/ug_course_page.php

Also roll PP to live (PR already merged: https://github.com/unikent/programmes-plant/pull/911)

Roll to live (for Friday)

---

app/views/pg/tabs/overview.php
app/views/ug/tabs/overview.php

https://trello.com/c/wEuiuCnO/216-remove-contact-or-order-a-prospectus-text-at-bottom-of-ug-and-pg

remove bullets

---

app/views/partials/profile-quote.php
app/views/pg/tabs/careers.php
app/views/ug/tabs/careers.php
app/views/ug/tabs/entry.php

add careers_profile quote to careers tabs using a partial for blockquote output of a student profile object.

add careers_profile

---

app/views/pg/course.php
app/views/ug/course.php

- moved year display above links and buttons
- tidied up links and buttons slightly

modified mobile layout of year display

---

public/css/module-catalogue.css

- also fixed some positioning of the search bar

fixes to breadcrumb visibility on mobile

---

app/views/partials/stage.php
app/views/pg/tabs/structure.php

- d-block forces display:block, but also forces full-width link

removed d-block

---

app/views/partials/stage.php
public/css/courses.css

- fixed issues with jumpy display
- now have to click on the title to close the module text

better display of course module data

---

app/views/partials/stage.php
public/css/courses.css

Revert "better display of course module data"

---

app/controllers/CoursesController.php

preview fix for ug

---

README.md

These changes enable or disable certain links and banners displayed during clearing.

Added short note to readme about config values for clearing

---

app/views/partials/profile-feature.php
public/css/courses.css

- carousel overflow changed to hidden. Moved blue link block so it's still visible
- also changed the quote so it's a link

fixed scrolling carousel bug

---

app/views/profile.php
app/views/profiles.php

- alumni/student filter added
- text changes

Changes to filters on student profiles

---

app/views/profiles.php

gets the alumni profiles listing markup in line with other quickspot searches

alumni profiles markup tweak

---

app/views/modules/module.php

As per CSAO's request, they have OK'd with EMS

Removed second year of module availability info

---

app/views/profile.php

- see also links are always shown.
- optional related courses links are shown above

showing related courses as a separate menu

---

app/views/ug/tabs/overview.php
public/css/courses.css

tef logo now drops below the text on mobile

altered the position of the tef logo on mobile

---

app/views/pg/contact-modal.php
app/views/ug/contact-modal.php
public/css/courses.css

See: https://trello.com/c/ZoIlgv8b/1451-contact-us-modal-changes-on-ug-and-pg

Implement new PG contact modal

---

app/views/partials/stage.php

Add stage_id to the module-code-more id used to identify module details to show / hide
so that it works for the same module repeated in multiple stages.

Toggle modules works for all instances of a module listed in different stages

---

app/views/partials/stage-2019-onwards.php

Test this by viewing the course structure for 2019 courses. See the text displayed below a optional and a compulsory module. 
Thanks to James P for reporting this so quickly.

Fixed misspell 

---

app/views/pg/tabs/overview.php

Copied from ref text for undergraduate

Added research intensity logo and text

---

app/views/partials/notices.php
public/css/courses.css

Dummy mark up for UX to make beautiful and useful.
Replies on a number of immutable fields to exist in Programmes Plant. Field config is...
- 'Open Day Banner Heading' - text
- 'Open Day Banner Text' - textarea
- 'Open Day Banner - Display Banner' - select, options 'true,false' - initial value 'false' 
- 'Open Day Banner Target URL' - text
- 'Open Day Banner - Call to Action button text' - text
all fields should be editable by admin

WIP: Open Days Banner

---

app/views/ug/course.php

See https://trello-attachments.s3.amazonaws.com/556d769a202ef3a77e3603fc/5d77badf686aa4894b11af2b/ca7d1a148b31c74a4f8bc40194fe7fbd/Guidance_for_display_and_implementation_of_the_Discover_Uni_(Unistats)_widget_(2019_updated).docx for details on the implementation of the newer code

add new discover uni code to course pages
